/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f1xx.h"
#include "stm32f1xx_hal_gpio.h"
///mnt/d/dev/SuperProject/VS_STM32/STM32_ver1/build/STM32_ver1.elf
#define TRIG_PIN GPIO_PIN_9
#define ECHO_PIN GPIO_PIN_8
#define ULTRASONIC_GPIO GPIOA

void ultrasonic_init(void) {
    // Enable GPIOA clock
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
    // Set TRIG (A9) as output push-pull
    ULTRASONIC_GPIO->CRH &= ~(GPIO_CRH_MODE9 | GPIO_CRH_CNF9);
    ULTRASONIC_GPIO->CRH |= (GPIO_CRH_MODE9_1); // Output 2MHz
    // Set ECHO (A8) as input floating
    ULTRASONIC_GPIO->CRH &= ~(GPIO_CRH_MODE8 | GPIO_CRH_CNF8);
    ULTRASONIC_GPIO->CRH |= GPIO_CRH_CNF8_0;
}

uint32_t ultrasonic_read(void) {
    // Send 10us pulse to TRIG
    ULTRASONIC_GPIO->BSRR = TRIG_PIN;
    for (volatile int i = 0; i < 80; i++); // ~10us delay
    ULTRASONIC_GPIO->BRR = TRIG_PIN;

    // Wait for ECHO to go high
    uint32_t timeout = 30000;
    while (!(ULTRASONIC_GPIO->IDR & ECHO_PIN) && --timeout);
    if (!timeout) return 0;

    // Measure high time
    uint32_t t = 0;
    while (ULTRASONIC_GPIO->IDR & ECHO_PIN) {
        t++;
    }
    // Convert ticks to microseconds (approximate)
    // Assuming each loop ~1us, adjust for your clock
    return t;
}

int main(void)
{
    ultrasonic_init();
    uint32_t distance;
    while (1) {
        uint32_t duration = ultrasonic_read();
        distance = duration / 58;
        printf("Distance: %lu cm\r\n", distance); // In ra UART hoặc SWO
        for (volatile int d = 0; d < 100000; d++); // Delay đơn giản
    }
}
