#!/usr/bin/env bash
# Stop hook — auto-appends a lightweight activity entry after each Claude response.
# Tracks which source files were modified in the last 3 hours.

AGENT_DIR="/home/nvidia/Documents/agent"
PROJECT_DIR="/home/nvidia/Documents"
LOG_FILE="$AGENT_DIR/history/$(date +%Y-%m-%d)_activity.md"

# Create log file with header if new today
if [ ! -f "$LOG_FILE" ]; then
    cat > "$LOG_FILE" << EOF
# Activity log — $(date +%Y-%m-%d)

_Auto-generated by session_logger.sh. Replace with a proper session summary when done._

EOF
fi

# Files modified in last 3 hours
RECENT=$(find "$PROJECT_DIR" \
    \( -name "*.cpp" -o -name "*.hpp" -o -name "*.py" -o -name "*.h" -o -name "*.ino" \) \
    -not -path "*/build/*" \
    -mmin -180 \
    -printf "  - %P\n" 2>/dev/null | sort -u)

# Only append if files were modified
if [ -n "$RECENT" ]; then
    cat >> "$LOG_FILE" << EOF

## $(date +%H:%M) — files touched
$RECENT

EOF
fi
