; PlatformIO Project Configuration - Fan Controller
; Arduino Uno + N-Channel MOSFET + Quạt DC 12V 3-chân
; PWM -> Pin 5 (Gate MOSFET)  |  TACH -> Pin 2 (INT0)

[platformio]
src_dir = .

[env:fan]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
monitor_eol = LF
monitor_filters = time, colorize
; EEPROM & interrupt built-in, no extra lib_deps needed
