#!/usr/bin/env python3
"""Generate a Doxygen INPUT_FILE_ENCODING fragment for mixed-encoding sources.

The DBM tree mixes UTF-8 (e.g. adcensus/) with Shift-JIS / CP932 files that carry
Japanese comments. Doxygen defaults to reading everything as INPUT_ENCODING
(UTF-8 here); a Shift-JIS file then mis-parses — worst case, a double-byte char
whose 2nd byte is 0x5C ('\\') swallows the following code token and the function
loses its <references>, breaking the call graph.

This pre-pass classifies every source file: anything that does NOT decode as
UTF-8 is mapped to CP932 (Windows superset of Shift-JIS, covers JIS symbols like
▲). It writes a fragment to be @INCLUDE'd from the Doxyfile so the originals are
never touched.

Usage:
    python gen_encoding_map.py --roots testtool com/project \
        --out doxygen_out/encoding.inc
"""

from __future__ import annotations

import argparse
import os
import sys

# Mirror the Doxyfile FILE_PATTERNS so we classify exactly what Doxygen parses.
SOURCE_EXTS = (".c", ".cc", ".cpp", ".cxx", ".h", ".hh", ".hpp", ".hxx")
# Mirror EXCLUDE_PATTERNS — never classify build artifacts / vendored trees.
SKIP_DIRS = ("build", "third_party", "captures", ".git")
# Encoding assigned to files that are not valid UTF-8.
NONUTF8_ENCODING = "CP932"


def is_source(name: str) -> bool:
    return name.lower().endswith(SOURCE_EXTS)


def is_utf8(path: str) -> bool:
    try:
        with open(path, "rb") as fh:
            fh.read().decode("utf-8")
        return True
    except (UnicodeDecodeError, OSError):
        return False


def scan(roots: list[str]) -> list[str]:
    """Return relative paths (forward slashes) of non-UTF-8 source files."""
    hits: list[str] = []
    for root in roots:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fn in filenames:
                if not is_source(fn):
                    continue
                full = os.path.join(dirpath, fn)
                if not is_utf8(full):
                    hits.append(full.replace(os.sep, "/"))
    return sorted(hits)


def write_fragment(paths: list[str], out: str) -> None:
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by tools/gen_encoding_map.py — do not edit by hand.\n")
        fh.write("# Maps non-UTF-8 (Shift-JIS) sources to CP932 so Doxygen parses\n")
        fh.write("# them correctly and the call graph keeps its <references>.\n")
        if not paths:
            fh.write("# (no non-UTF-8 files found)\n")
            fh.write("INPUT_FILE_ENCODING =\n")
            return
        # Leading '*' makes each pattern match regardless of how Doxygen
        # anchors the path (relative vs absolute prefix).
        entries = [f"*{p}={NONUTF8_ENCODING}" for p in paths]
        fh.write("INPUT_FILE_ENCODING = " + " \\\n".join(entries) + "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate Doxygen INPUT_FILE_ENCODING map.")
    ap.add_argument("--roots", nargs="+", default=["testtool", "com/project"],
                    help="Input roots (mirror the Doxyfile INPUT line).")
    ap.add_argument("--out", default="doxygen_out/encoding.inc",
                    help="Doxyfile fragment to write.")
    args = ap.parse_args(argv)

    paths = scan(args.roots)
    write_fragment(paths, args.out)
    print(f"[info] scanned {args.roots}: {len(paths)} non-UTF-8 file(s) "
          f"mapped to {NONUTF8_ENCODING} -> {args.out}")
    for p in paths:
        print(f"  [cp932] {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
