#!/usr/bin/env python3
"""Generate slam/config/camera.yaml from a field-of-view estimate (plan A3, no checkerboard).

For a generic webcam with no datasheet, intrinsics can be approximated from the
horizontal FOV instead of measured with a checkerboard:

    fx = fy = (width / 2) / tan(HFOV / 2)
    cx, cy  = image center
    distortion = 0   (assumed; a checkerboard is the only way to recover it)

This is the SAME approximation deepmap/build_map.py uses. Good enough for a first
RTAB-Map run; if walls visibly bow or the map scales wrong, do a one-time
checkerboard calibration to refine fx/fy and add distortion.

  python slam/make_intrinsics.py                 # 60 deg HFOV @ 640x480 (default)
  python slam/make_intrinsics.py --hfov 70 --width 1280 --height 720
"""
import argparse
import math
import os

_OUT = os.path.expanduser('~/Documents/slam/config/camera.yaml')


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--hfov', type=float, default=60.0, help='horizontal FOV (deg)')
    ap.add_argument('--width', type=int, default=640)
    ap.add_argument('--height', type=int, default=480)
    args = ap.parse_args()

    fx = (args.width / 2.0) / math.tan(math.radians(args.hfov) / 2.0)
    fy = fx                      # square-pixel assumption
    cx, cy = args.width / 2.0, args.height / 2.0

    yaml = f"""# Mono intrinsics for /dev/video0 (plan A3) — FOV-DERIVED, no checkerboard.
# Generated by slam/make_intrinsics.py --hfov {args.hfov} --width {args.width} --height {args.height}
# fx = (W/2)/tan(HFOV/2); distortion assumed 0. Re-run with a measured HFOV, or do
# a checkerboard calibration, if the map bows or scales wrong.
image_width: {args.width}
image_height: {args.height}
camera_name: rgb
camera_matrix:
  rows: 3
  cols: 3
  data: [{fx:.2f}, 0.0,    {cx:.1f},
         0.0,    {fy:.2f}, {cy:.1f},
         0.0,    0.0,    1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,  0.0, 1.0, 0.0,  0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [{fx:.2f}, 0.0,    {cx:.1f}, 0.0,
         0.0,    {fy:.2f}, {cy:.1f}, 0.0,
         0.0,    0.0,    1.0,   0.0]
"""
    with open(_OUT, 'w') as fh:
        fh.write(yaml)
    print(f"Wrote {_OUT}")
    print(f"  HFOV={args.hfov} deg @ {args.width}x{args.height}  ->  "
          f"fx=fy={fx:.2f}, cx={cx:.1f}, cy={cy:.1f}, distortion=0")


if __name__ == '__main__':
    main()
