// Step_Dir_Driver — turns RM's StepCommand into real pulses.
//
// Each wheel owns its own LEDC high-speed timer, because each wheel runs at its
// own frequency. The pulse train is generated by the peripheral, never by the
// CPU: that is what stops UART parsing or a servo update from jittering the
// step timing, which would show up as a real position error the odometry cannot
// see (there is no encoder).
#ifndef FW_STEP_DIR_DRIVER_H
#define FW_STEP_DIR_DRIVER_H

#include "RM/driver_stepdir.h"

namespace fw {

class StepDirDriver {
public:
    StepDirDriver();

    // Configures three timers, three channels and three DIR pins.
    bool begin();

    // Applies one wheel's pulse rate and direction. A rate below
    // cfg::STEP_MIN_HZ switches the channel off instead of emitting a
    // sub-hertz pulse train.
    void apply(int wheel, const rm::StepCommand& command);

    // Silences every channel. Used on a failed init, so a half-configured
    // driver never leaves a wheel turning.
    void stopAll();

private:
    bool ready_;
};

}  // namespace fw

#endif  // FW_STEP_DIR_DRIVER_H
